sites:
  - name: "Raphael"
    sitemap_urls:
      - "https://raphael.app/sitemap.xml"
    active: true
  - name: "DesignArena"
    sitemap_urls:
      - "https://www.designarena.ai/sitemap.xml"
    active: true
  - name: "ImageGenerators"
    sitemap_urls:
      - "https://imagegenerators.ai/sitemap.xml"
    active: true
  - name: "AdCreative"
    sitemap_urls:
      - "https://www.adcreative.ai/sitemap.xml"
    active: true
  - name: "Canva"
    sitemap_urls:
      - "https://www.canva.com/sitemap.xml"
    active: true
  - name: "NoteGPT"
    sitemap_urls:
      - "https://notegpt.io/sitemap.xml"
    active: true


feishu:
  webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/d2ded826-3cb9-4521-8220-d63b7e34fef1"
  secret: ""

storage:
  retention_days: 7
  data_dir: "./data"
